//! Golden-snapshot harness for Timendus's IBM-logo ROM (ADR 0004).
//!
//! CI on the matrix (ubuntu-latest, macos-latest) runs the same bytes a
//! developer does — that cross-runner determinism is the whole point.
//!
//! `UPDATE_GOLDENS=1` rewrites the snapshot on the developer machine; commit
//! the regenerated bytes to lock in the new expectation.
//!
//! Files are read at runtime (not via `@embedFile`) because Zig restricts
//! `@embedFile` to paths inside the module's package directory; with
//! `chippy_core` rooted at `src/core/`, `tests/test_roms/` (per ADR 0004) is
//! out of reach. `zig build test` runs with CWD = repo root, so relative
//! paths under `tests/` resolve consistently across local and CI runs.

const std = @import("std");
const Machine = @import("machine.zig").Machine;
const Framebuffer = @import("display.zig").Framebuffer;
const display = @import("display.zig");
const bus_mod = @import("bus.zig");

const ROM_PATH = "tests/test_roms/ibm_logo.ch8";
const GOLDEN_PATH = "tests/test_goldens/ibm_logo_after_100_cycles.bin";
// Bumped 30→100 for M3.3 vBlank-wait stall budget; see ADR 0012. Captured
// bytes unchanged (vanilla JP-self loop is framebuffer-stable beyond N≈14).
const CYCLE_COUNT: u32 = 100;
const PACKED_BYTES: usize = display.PIXELS / 8;

/// Row-major, MSB = leftmost pixel — the standard CHIP-8 sprite-pack layout,
/// chosen so a hex dump of the snapshot reads visually like the screen.
fn packFramebuffer(fb: *const Framebuffer) [PACKED_BYTES]u8 {
    var out: [PACKED_BYTES]u8 = [_]u8{0} ** PACKED_BYTES;
    for (0..display.HEIGHT) |row| {
        for (0..display.WIDTH / 8) |byte_col| {
            var b: u8 = 0;
            for (0..8) |bit| {
                const px = fb.get(byte_col * 8 + bit, row);
                b |= @as(u8, px) << @intCast(7 - bit);
            }
            out[row * (display.WIDTH / 8) + byte_col] = b;
        }
    }
    return out;
}

fn updateGoldensRequested() bool {
    const v = std.testing.environ.getPosix("UPDATE_GOLDENS") orelse return false;
    return std.mem.eql(u8, v, "1");
}

test "IBM logo: framebuffer after 100 cycles matches golden" {
    const cwd = std.Io.Dir.cwd();
    const io = std.testing.io;

    const rom = try cwd.readFileAlloc(io, ROM_PATH, std.testing.allocator, .limited(bus_mod.ROM_MAX_BYTES));
    defer std.testing.allocator.free(rom);

    var m = Machine.init(.{});
    defer m.deinit();
    try m.loadRom(rom);
    _ = m.runCycles(CYCLE_COUNT);

    const actual = packFramebuffer(&m.framebuffer);

    if (updateGoldensRequested()) {
        try cwd.writeFile(io, .{ .sub_path = GOLDEN_PATH, .data = &actual });
        return;
    }

    const golden = try cwd.readFileAlloc(io, GOLDEN_PATH, std.testing.allocator, .limited(PACKED_BYTES + 1));
    defer std.testing.allocator.free(golden);

    try std.testing.expectEqualSlices(u8, golden, &actual);
}
