//! Golden-snapshot harness for Timendus's corax+ opcode self-test (ADR 0004).
//!
//! Keystone gate for M2: corax+ exercises subroutines, conditional skips, the
//! ALU, indexed jump, address-register arithmetic, BCD, bulk register memory
//! load/store, font lookup, and shifts — every opcode this milestone added.
//! CI on the matrix (ubuntu-latest, macos-latest) runs the same bytes a
//! developer does — that cross-runner determinism is the whole point.
//!
//! `UPDATE_GOLDENS=1` rewrites the snapshot on the developer machine; commit
//! the regenerated bytes to lock in the new expectation.
//!
//! See the file-level doc in `golden_ibm_logo.zig` for the runtime-read /
//! `@embedFile` package-path constraint that motivates the relative-path
//! load pattern shared with that test.

const std = @import("std");
const Machine = @import("machine.zig").Machine;
const Framebuffer = @import("display.zig").Framebuffer;
const display = @import("display.zig");
const bus_mod = @import("bus.zig");

const ROM_PATH = "tests/test_roms/corax_plus.ch8";
const GOLDEN_PATH = "tests/test_goldens/corax_plus_after_1000_cycles.bin";
const CYCLE_COUNT: u32 = 1000;
const PACKED_BYTES: usize = display.PIXELS / 8;

/// Row-major, MSB = leftmost pixel — the standard CHIP-8 sprite-pack layout,
/// chosen so a hex dump of the snapshot reads visually like the screen.
fn packFramebuffer(fb: *const Framebuffer) [PACKED_BYTES]u8 {
    var out: [PACKED_BYTES]u8 = [_]u8{0} ** PACKED_BYTES;
    for (0..display.HEIGHT) |row| {
        for (0..display.WIDTH / 8) |byte_col| {
            var b: u8 = 0;
            for (0..8) |bit| {
                const px = fb.get(byte_col * 8 + bit, row);
                b |= @as(u8, px) << @intCast(7 - bit);
            }
            out[row * (display.WIDTH / 8) + byte_col] = b;
        }
    }
    return out;
}

fn updateGoldensRequested() bool {
    const v = std.testing.environ.getPosix("UPDATE_GOLDENS") orelse return false;
    return std.mem.eql(u8, v, "1");
}

test "corax+: framebuffer after 1000 cycles matches golden" {
    const cwd = std.Io.Dir.cwd();
    const io = std.testing.io;

    const rom = try cwd.readFileAlloc(io, ROM_PATH, std.testing.allocator, .limited(bus_mod.ROM_MAX_BYTES));
    defer std.testing.allocator.free(rom);

    var m = Machine.init(.{});
    defer m.deinit();
    try m.loadRom(rom);
    _ = m.runCycles(CYCLE_COUNT);

    const actual = packFramebuffer(&m.framebuffer);

    if (updateGoldensRequested()) {
        try cwd.writeFile(io, .{ .sub_path = GOLDEN_PATH, .data = &actual });
        return;
    }

    const golden = try cwd.readFileAlloc(io, GOLDEN_PATH, std.testing.allocator, .limited(PACKED_BYTES + 1));
    defer std.testing.allocator.free(golden);

    try std.testing.expectEqualSlices(u8, golden, &actual);
}
